name: Build and Attest

on:
  push:
    branches: [ master ]  # Make sure this matches your branch

permissions:
  id-token: write   # Needed to sign the attestation
  contents: write   # Needed to upload the attestation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the project
        run: |
          mkdir -p dist
          echo "sample artifact" > dist/output.txt

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist/output.txt"
